USE [master]
GO

/****** Object:  Database [Incendo]    Script Date: 16/03/2022 17:59:00 ******/
CREATE DATABASE [Incendo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Incendo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Incendo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Incendo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Incendo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Incendo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Incendo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Incendo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Incendo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Incendo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Incendo] SET ARITHABORT OFF 
GO

ALTER DATABASE [Incendo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Incendo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Incendo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Incendo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Incendo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Incendo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Incendo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Incendo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Incendo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Incendo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Incendo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Incendo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Incendo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Incendo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Incendo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Incendo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Incendo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Incendo] SET RECOVERY FULL 
GO

ALTER DATABASE [Incendo] SET  MULTI_USER 
GO

ALTER DATABASE [Incendo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Incendo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Incendo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Incendo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Incendo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Incendo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Incendo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Incendo] SET  READ_WRITE 
GO

